[package]
name = "scooper-v2"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/rrruko/scooper-v2"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
hex = "0.4.3"
minicbor = { version = "2.1.1", features = ["alloc", "derive"] }
num-bigint = "0.4.6"
pallas-addresses = "0.33.0"
pallas-codec = "0.33.0"
pallas-crypto = "0.33.0"
pallas-network = "0.33.0"
pallas-primitives = "0.33.0"
pallas-traverse = "0.33.0"
tokio = { version = "1.46.1", features = ["full"] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
