[package]
name = "scooper-v2"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/rrruko/scooper-v2"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
pallas-network = "0.33.0"
tokio = { version = "1.46.1", features = ["full"] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
