[global.startup]
# Network selection (mainnet or preview)
network-name = "preview"
# Use Mithril to quick sync without a local node
method = "mithril"  # Options: "mithril" | "snapshot"

# Upstream peers configuration (example: ["backbone.cardano.iog.io:3001", "backbone.mainnet.emurgornd.com:3001"])
[module.peer-network-interface]
node-addresses = ["mithril-signer-1.testing-preview.api.mithril.network:9091"]

# Mithril configuration
[module.mithril-snapshot-fetcher]
aggregator-url = "https://aggregator.pre-release-preview.api.mithril.network/aggregator"
genesis-key = "5b3132372c37332c3132342c3136312c362c3133372c3133312c3231332c3230372c3131372c3139382c38352c3137362c3139392c3136322c3234312c36382c3132332c3131392c3134352c31332c3233322c3234332c34392c3232392c322c3234392c3230352c3230352c33392c3233352c34345d"
# Download max age in hours. E.g. 8 means 8 hours (if there isn't any snapshot within this time range download from Mithril)
download-max-age = "never"